### ISSUE TITLE
Show `best_params_` for classification?

### ISSUE THREAD

**Issue by ttimbers** [UBC-DSCI/introduction-to-datascience-python#281] opened 2023-11-10 20:50 UTC
in the Python version, for classification we don't save the object that we would ask for `best_params_` from, so unless students read the regression chapter and extrapolate to that they will have a hard time. They will think they need to make a data frame of all the parameters and their scores, and sort it and grab the value.

In some sense, it is good to get the values from the data frame, as you should really look at more than just one number, but if you do agree with the best param suggested by the CV procedure, then programmatically its nice to have these.

**Comment by ttimbers** [comment] 2023-11-10 20:51
This also might be a nice improvement for the R book for `tidymodels` if a similar attribute exists after CV tuning

**Comment by trevorcampbell** [comment] 2023-11-10 21:14
This may be a duplicate of #205 -- I will check this and that previous issue later

**Comment by trevorcampbell** [comment] 2023-11-11 04:28
yep duplicate, but i'll leave this open for now until there's a PR or otherwise closure

**Comment by joelostblom** [comment] 2023-11-12 19:42
> for classification we don't save the object that we would ask for best_params_ from

We actually do save the object since `.fit` is an inplace operation and we call it when getting the results dataframe:

![image](https://github.com/UBC-DSCI/introduction-to-datascience-python/assets/4560057/f648a1a1-23f7-489e-9c4a-72af5b793774)
(I added the last line just to show that `cancer_tune_grid` is modified in place)

I agree that it would be nice to show `best_params_` explicitly here as per #205 and I also think we should be more explicit and consistent when using `fit` as per https://github.com/UBC-DSCI/introduction-to-datascience-python/issues/233 and #134.

**Closed as completed** 2023-11-13 01:27 UTC
Labels: duplicate
